# Generated by Django 2.2.24 on 2021-06-12 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя человека', max_length=255)),
                ('dob', models.DateField(default='1970-01-01')),
                ('birthplace', models.TextField(default='Место рождения')),
                ('biography', models.TextField(default='Бмография человека')),
                ('image', models.ImageField(upload_to='persons')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Series name', max_length=50)),
                ('description', models.TextField(default='Series description')),
                ('year', models.IntegerField(default='1970')),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='series')),
                ('age_restrictions', models.CharField(default='0+', max_length=3)),
                ('actors', models.ManyToManyField(related_name='seriesactors', to='catalog.Person')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriesdirector', to='catalog.Person')),
                ('screenwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriesscreenwriter', to='catalog.Person')),
                ('tags', models.ManyToManyField(to='catalog.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Film name', max_length=50)),
                ('description', models.TextField(default='Film description')),
                ('year', models.IntegerField(default='1970')),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='films')),
                ('budget', models.CharField(default='0.00$', max_length=50)),
                ('age_restrictions', models.CharField(default='0+', max_length=3)),
                ('actors', models.ManyToManyField(related_name='actors', to='catalog.Person')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='catalog.Person')),
                ('screenwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenwriter', to='catalog.Person')),
                ('tags', models.ManyToManyField(to='catalog.Tag')),
            ],
        ),
    ]
