# Generated by Django 3.2.9 on 2021-11-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('state', models.CharField(choices=[('+', 'Positive'), ('=', 'Neutral'), ('-', 'Negative')], max_length=1)),
                ('object_type', models.CharField(choices=[('f', 'film'), ('s', 'series'), ('p', 'person')], max_length=1)),
                ('object_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
